"""empty message

Revision ID: 12aa8ae2bc02
Revises:
Create Date: 2025-07-07 22:13:04.291665

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12aa8ae2bc02"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("date_create", sa.DateTime(), nullable=True)
    )
    op.alter_column(
        "users",
        "username",
        existing_type=sa.VARCHAR(length=100),
        nullable=True,
    )
    op.drop_column("users", "extra")
    op.drop_column("users", "marketplace")
    op.drop_column("users", "expectations")
    op.drop_column("users", "about")
    op.drop_column("users", "is_complete")
    op.drop_column("users", "category")
    op.drop_column("users", "role")
    op.drop_column("users", "achievements")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "achievements", sa.TEXT(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "role", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "category",
            sa.VARCHAR(length=250),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "is_complete", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column("about", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "users",
        sa.Column(
            "expectations", sa.TEXT(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "marketplace",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column("extra", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.alter_column(
        "users",
        "username",
        existing_type=sa.VARCHAR(length=100),
        nullable=False,
    )
    op.drop_column("users", "date_create")
    # ### end Alembic commands ###
