"""empty message

Revision ID: 4e02d7fca165
Revises: 925226f75dd5
Create Date: 2025-07-08 14:24:33.054505

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e02d7fca165"
down_revision: Union[str, Sequence[str], None] = "925226f75dd5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts", sa.Column("role", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "posts", sa.Column("marketplace", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "posts", sa.Column("category", sa.String(length=255), nullable=True)
    )
    op.add_column("posts", sa.Column("achievements", sa.Text(), nullable=True))
    op.add_column("posts", sa.Column("about", sa.Text(), nullable=True))
    op.add_column("posts", sa.Column("expectations", sa.Text(), nullable=True))
    op.add_column("posts", sa.Column("extra", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "extra")
    op.drop_column("posts", "expectations")
    op.drop_column("posts", "about")
    op.drop_column("posts", "achievements")
    op.drop_column("posts", "category")
    op.drop_column("posts", "marketplace")
    op.drop_column("posts", "role")
    # ### end Alembic commands ###
