"""empty message

Revision ID: 577a5ceb7cd8
Revises: 4e02d7fca165
Create Date: 2025-07-10 21:55:29.630577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '577a5ceb7cd8'
down_revision: Union[str, Sequence[str], None] = '4e02d7fca165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_type', sa.String(length=20), nullable=False))
    op.add_column('posts', sa.Column('contact', sa.String(length=100), nullable=False))
    op.add_column('posts', sa.Column('services', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('cases', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('position', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('requirements', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('photos', postgresql.ARRAY(sa.String()), nullable=True))
    op.alter_column('posts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('posts', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('posts', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('posts', 'about',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('posts', 'extra')
    op.drop_column('posts', 'category')
    op.drop_column('posts', 'marketplace')
    op.drop_column('posts', 'expectations')
    op.drop_column('posts', 'achievements')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('achievements', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('expectations', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('marketplace', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('extra', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('posts', 'about',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('posts', 'role',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('posts', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('posts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('posts', 'photos')
    op.drop_column('posts', 'requirements')
    op.drop_column('posts', 'position')
    op.drop_column('posts', 'cases')
    op.drop_column('posts', 'services')
    op.drop_column('posts', 'contact')
    op.drop_column('posts', 'post_type')
    # ### end Alembic commands ###
